# Generated by Django 3.2.8 on 2021-10-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_auto_20211020_0847"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="test"),
            preserve_default=False,
        ),
    ]
